version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pongapp
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  back:
    build: ./Server
    ports:
      - '5432:5432'
  back:
    build: ./Server
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /usr/src/app/node_modules
      - ./Server:/usr/src/app
  front:
    build: ./FrontEnd
    ports:
      - "3001:3001"
    volumes:
      - /usr/src/app/node_modules
      - ./FrontEnd:/usr/src/app
    restart: always
    environment:
       - CHOKIDAR_USEPOLLING=true
    command: "npm start"  
volumes:
  # backend:
  #   driver: local
  # FrontEnd :
  #   driver : local
  # pgadmin-data:
  db:
    driver: local